defaults: &defaults
   title:         'GAOC Ranking System'
   header_image:  'GAOClogo.jpg'
   admin_pwd:     <%= ENV["ADMIN_PWD"] || 'not_very_secret' %>
   season:        '17/18'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
